# Generated by Django 6.1.1 on 2026-10-01 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('imagen', models.ImageField(blank=True, upload_to='habitaciones/')),
                ('caracteristicas', models.TextField(help_text='Una característica por línea')),
                ('orden', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'habitaciones',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre y apellido')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('leido', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('llegada', models.DateField()),
                ('salida', models.DateField()),
                ('adultos', models.PositiveSmallIntegerField(default=1)),
                ('ninos', models.PositiveSmallIntegerField(default=0, verbose_name='niños')),
                ('nombre', models.CharField(blank=True, max_length=120)),
                ('contacto', models.CharField(blank=True, max_length=120)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
    ]
